# Automatically generated by Updater v1.0
# @author Daniel J. Finnegan

import shutil, os, os.path, sys
from subprocess import call

if __name__ == '__main__':
    project_root = os.getcwd()
    shutil.rmtree(os.path.join (project_root, 'bin'), ignore_errors=True)
    os.mkdir(os.path.join(project_root, 'bin'))

    os.chdir(os.path.join(project_root, 'bin'))
    call(['cmake', '..', '-DCMAKE_INSTALL_PREFIX=Lancophone'])
    call(['cmake', '--build', '.'])
    call(['cpack'])
